'use client';
import { useState } from 'react';
import { LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer } from 'recharts';
import { ChartNoAxesCombined,Info } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Table,TableHeader,TableHead,TableBody,TableRow,TableCell } from '@/components/ui/table';
import { calculateTotals,compareTotals,investmentResult,money,monthLabel,previousMonth,type PortfolioState,type Entry } from '@/lib/finance';

const shown=(value:number|null|undefined)=>value==null?'—':money(value);
const completeTotal=(entries:Entry[])=>entries.every(e=>e.value!=null)?calculateTotals(entries).total:null;
const shortMonth=(month:string)=>new Date(month+'-15T12:00:00').toLocaleDateString('pt-BR',{month:'short',year:'numeric'});

export default function Analytics({state,onOpen}:{state:PortfolioState;onOpen:(month:string)=>void}){
 const closed=state.closings.filter(c=>c.status==='closed').sort((a,b)=>a.month.localeCompare(b.month));
 const [startChoice,setStart]=useState(''),[endChoice,setEnd]=useState(''),[accountChoice,setAccount]=useState('total');
 const end=closed.find(c=>c.month===endChoice)??closed.at(-1);
 const start=closed.find(c=>c.month===startChoice)??closed.at(-2);
 const accounts=Array.from(new Map(closed.flatMap(c=>c.entries.map(e=>[e.accountId,e.name] as const))).entries());
 const account=accountChoice==='total'||accounts.some(([id])=>id===accountChoice)?accountChoice:'total';
 if(!end)return <section className="panel welcome"><div className="welcome-icon"><ChartNoAxesCombined size={35}/></div><h2>Seu histórico começa no primeiro fechamento</h2><p>Conclua um mês para acompanhar os saldos. Com dois meses concluídos, você poderá comparar seu patrimônio e cada conta.</p></section>;
 const currentTotal=completeTotal(end.entries),priorTotal=start?completeTotal(start.entries):null;
 const comparison=compareTotals(currentTotal??0, currentTotal===null?null:priorTotal);
 const ids=Array.from(new Set([...(start?.entries??[]).map(e=>e.accountId),...end.entries.map(e=>e.accountId)]));
 const rows=ids.map(id=>({id,before:start?.entries.find(e=>e.accountId===id),after:end.entries.find(e=>e.accountId===id)})).filter(r=>account==='total'||r.id===account);
 const newCount=start?rows.filter(r=>!r.before&&r.after).length:0,absentCount=start?rows.filter(r=>r.before&&!r.after).length:0;
 const lower=start&&start.month<end.month?start.month:end.month,upper=start&&start.month>end.month?start.month:end.month;
 const range=closed.filter(c=>c.month>=lower&&c.month<=upper);
 const calendar:string[]=[];let cursor=upper;for(let i=0;cursor>=lower&&i<3600;i++,cursor=previousMonth(cursor))calendar.unshift(cursor);
 const series=calendar.map(month=>{const c=range.find(c=>c.month===month),e=c?.entries.find(e=>e.accountId===account);const cents=!c?null:account==='total'?completeTotal(c.entries):e?.value??null;return {month,value:cents===null?null:cents/100};});
 const investmentEntries=end.entries.filter(e=>e.type==='investment'&&(account==='total'||e.accountId===account));
 const appEntries=investmentEntries.filter(e=>e.investmentMode==='result'),capitalEntries=investmentEntries.filter(e=>e.investmentMode!=='result');
 const resultSum=(entries:Entry[])=>entries.length&&entries.every(e=>investmentResult(e)!==null)?entries.reduce((sum,e)=>sum+investmentResult(e)!,0):null;
 return <div className="analytics-page">
  <section className="panel analytics-controls"><div><h2>Compare seus fechamentos</h2><p>Selecione dois meses concluídos e acompanhe os saldos no intervalo entre eles.</p></div><div className="analytics-filters">
   <div><label htmlFor="analysis-start">Mês de referência</label><Select value={start?.month??''} onValueChange={setStart} disabled={closed.length<2}><SelectTrigger id="analysis-start"><SelectValue placeholder="Mais um fechamento necessário"/></SelectTrigger><SelectContent>{closed.map(c=><SelectItem key={c.month} value={c.month}>{monthLabel(c.month)}</SelectItem>)}</SelectContent></Select></div>
   <div><label htmlFor="analysis-end">Mês comparado</label><Select value={end.month} onValueChange={setEnd}><SelectTrigger id="analysis-end"><SelectValue/></SelectTrigger><SelectContent>{closed.map(c=><SelectItem key={c.month} value={c.month}>{monthLabel(c.month)}</SelectItem>)}</SelectContent></Select></div>
   <div><label htmlFor="analysis-account">Conta ou patrimônio</label><Select value={account} onValueChange={setAccount}><SelectTrigger id="analysis-account"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="total">Patrimônio total</SelectItem>{accounts.map(([id,name])=><SelectItem key={id} value={id}>{name}</SelectItem>)}</SelectContent></Select></div>
  </div></section>
  {!start&&<div className="analytics-notice">Você tem um mês concluído. Conclua mais um para comparar a evolução; os saldos deste mês já estão disponíveis abaixo.</div>}
  <div className="analytics-metrics"><div className="metric primary-metric"><span>PATRIMÔNIO · {shortMonth(end.month)}</span><h2>{shown(currentTotal)}</h2><small>{currentTotal===null?'Há saldos não informados neste fechamento':'Soma das contas registradas no fechamento'}</small></div><div className="metric"><span>Variação patrimonial total</span><h2 className={comparison.difference!=null&&comparison.difference<0?'negative':'positive'}>{shown(comparison.difference)}</h2><small>{comparison.percent==null?'Percentual indisponível sem uma base válida':comparison.percent.toFixed(2).replace('.',',')+'% sobre o mês de referência'}{start&&<span> · {shortMonth(start.month)} → {shortMonth(end.month)}</span>}</small></div><div className="metric"><span>Resultado informado pelo app</span><h2>{shown(resultSum(appEntries))}</h2><small>{appEntries.length?`${appEntries.length} investimento(s) · ${shortMonth(end.month)}`:'Nenhum investimento nesta modalidade'}</small></div><div className="metric"><span>Resultado calculado pelo capital</span><h2>{shown(resultSum(capitalEntries))}</h2><small>{capitalEntries.length?`${capitalEntries.length} investimento(s) · ${shortMonth(end.month)}`:'Nenhum investimento nesta modalidade'}</small></div></div>
  <section className="panel analytics-trend"><div className="section-heading"><div><h2>{account==='total'?'Evolução do patrimônio':accounts.find(([id])=>id===account)?.[1]}</h2><p>Fechamentos concluídos · {shortMonth(lower)} a {shortMonth(upper)}</p></div><span className="chart-legend"><i/> Saldo registrado</span></div>{series.length<2?<div className="empty-note">Selecione dois meses distintos para visualizar a trajetória.</div>:<><div role="img" aria-label={`Evolução dos saldos entre ${monthLabel(lower)} e ${monthLabel(upper)}. Os valores também estão na tabela abaixo.`}><ResponsiveContainer width="100%" height={270}><LineChart data={series} margin={{top:12,right:18,left:0,bottom:14}} accessibilityLayer><CartesianGrid vertical={false} stroke="#edf1f3"/><XAxis dataKey="month" tickFormatter={shortMonth} axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#73858e'}} minTickGap={20}/><YAxis width={70} axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#73858e'}} tickFormatter={n=>new Intl.NumberFormat('pt-BR',{notation:'compact',maximumFractionDigits:1}).format(n)}/><Tooltip formatter={(value)=>money(Number(value)*100)} labelFormatter={label=>monthLabel(String(label))} contentStyle={{borderRadius:10,border:'1px solid #e1e9ec'}}/><Line dataKey="value" name="Saldo" stroke="#3478f6" strokeWidth={3} dot={{r:3}} connectNulls={false}/></LineChart></ResponsiveContainer></div><p className="subtle analytics-caption">Valores em reais. Lacunas indicam conta ausente ou saldo não informado.</p></>}</section>
  <section className="panel analytics-table"><div className="section-heading"><div><h2>{start?'Comparação por conta':'Saldos do fechamento'}</h2><p>Os nomes e as categorias seguem os registros históricos de cada mês.</p></div><div className="analytics-open">{start&&<Button variant="outline" size="sm" onClick={()=>onOpen(start.month)}>Abrir {shortMonth(start.month)}</Button>}<Button variant="outline" size="sm" onClick={()=>onOpen(end.month)}>Abrir {shortMonth(end.month)}</Button></div></div><Table><TableHeader><TableRow><TableHead>Conta</TableHead>{start&&<TableHead className="text-right">{shortMonth(start.month)}</TableHead>}<TableHead className="text-right">{shortMonth(end.month)}</TableHead><TableHead className="text-right">Variação do saldo</TableHead><TableHead className="text-right">Resultado · {shortMonth(end.month)}</TableHead></TableRow></TableHeader><TableBody>{rows.map(({id,before,after})=>{const entry=after??before!,delta=before?.value!=null&&after?.value!=null?after.value-before.value:null;return <TableRow key={id}><TableCell><strong>{entry.name}</strong><small className="result-source">{entry.categoryName}{start&&!before?' · Nova neste comparativo':!after?' · Ausente no mês comparado':''}</small></TableCell>{start&&<TableCell className="text-right">{shown(before?.value)}</TableCell>}<TableCell className="text-right">{shown(after?.value)}</TableCell><TableCell className={'text-right '+(delta!=null&&delta<0?'negative':'positive')}>{shown(delta)}</TableCell><TableCell className="text-right">{after?.type==='investment'?shown(investmentResult(after)):'—'}{after?.type==='investment'&&<small className="result-source">{after.investmentMode==='result'?'Informado pelo app':'Calculado pelo capital'}</small>}</TableCell></TableRow>;})}</TableBody></Table>{!rows.length&&<p className="empty-note">Esta conta não aparece nos meses selecionados.</p>}<p className="subtle analytics-caption">— significa ausente, não informado ou sem base para comparar. Uma conta nova ou ausente não recebe variação de saldo.</p></section>
  {<section className="panel analytics-table"><div className="section-heading"><div><h2>Trajetória no intervalo</h2><p>Consulte os valores do gráfico ou abra um fechamento.</p></div></div><Table><TableHeader><TableRow><TableHead>Mês</TableHead><TableHead className="text-right">Saldo</TableHead><TableHead className="text-right">Fechamento</TableHead></TableRow></TableHeader><TableBody>{range.map(c=><TableRow key={c.month}><TableCell>{monthLabel(c.month)}</TableCell><TableCell className="text-right">{shown(account==='total'?completeTotal(c.entries):c.entries.find(e=>e.accountId===account)?.value)}</TableCell><TableCell className="text-right"><Button variant="ghost" size="sm" onClick={()=>onOpen(c.month)}>Abrir</Button></TableCell></TableRow>)}</TableBody></Table></section>}
  <div className="info-note"><Info size={17}/><span>A variação patrimonial inclui aportes, retiradas, movimentações e mudanças nas contas registradas; ela não representa rendimento. {newCount||absentCount?`Neste filtro, ${newCount} conta(s) nova(s) e ${absentCount} ausente(s) mudam o escopo da comparação. `:''}Os resultados dos investimentos são registrados separadamente no mês comparado e não representam o rendimento do intervalo.</span></div>
 </div>;
}

