'use client';
import { useState } from 'react';
import { Plus, Pencil, Trash2, Tags, Wallet } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { currentMonth, inputMoney, money, monthLabel, parseMoney, type PortfolioState } from '@/lib/finance';
import { budgetSummary, spendingCategories, type SpendingCategory } from '@/lib/life';

type Props={state:PortfolioState;busy:boolean;save:(op:any)=>Promise<boolean>;onDirty:(v:boolean)=>void};
type LimitDraft={category:SpendingCategory;value:string;month:string};
type CategoryDraft={id?:string;name:string;color:string};
export default function Budgets({state,busy,save,onDirty}:Props){
 const [month,setMonth]=useState(currentMonth),[limitDraft,setLimitDraft]=useState<LimitDraft|null>(null),[categoryDraft,setCategoryDraft]=useState<CategoryDraft|null>(null),[manager,setManager]=useState(false),[baseline,setBaseline]=useState(''),[error,setError]=useState(''),[pending,setPending]=useState(false),[removing,setRemoving]=useState<SpendingCategory|null>(null);
 const locked=busy||pending,rows=budgetSummary(state,month),categories=spendingCategories(state),budgeted=rows.filter(r=>r.limit!==null),unbudgeted=rows.filter(r=>r.limit===null),total=budgeted.reduce((a,r)=>({limit:a.limit+(r.limit??0),spent:a.spent+r.spent,pending:a.pending+r.pending}),{limit:0,spent:0,pending:0});
 const unbudgetedExpenses=(state.transactions??[]).filter(t=>t.kind==='expense'&&(t.status==='done'?t.settledDate?.slice(0,7):t.date.slice(0,7))===month&&!budgeted.some(r=>r.category.id===t.categoryId));
 const openLimit=(category:SpendingCategory,limit:number|null)=>{const d={category,value:inputMoney(limit),month};setLimitDraft(d);setBaseline(JSON.stringify(d));setError('');onDirty(false);};
 const openCategory=(category?:SpendingCategory)=>{const d={id:category?.id,name:category?.name??'',color:category?.color??'#00a57b'};setCategoryDraft(d);setBaseline(JSON.stringify(d));setError('');onDirty(false);};
 const closeEditor=()=>{if(locked)return;const draft=limitDraft??categoryDraft;if(draft&&JSON.stringify(draft)!==baseline&&!window.confirm('Descartar as alterações?'))return;setLimitDraft(null);setCategoryDraft(null);setError('');onDirty(false);};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(locked)return;setError('');try{let op:any;if(limitDraft){const value=parseMoney(limitDraft.value);if(value===null||value<=0)throw new Error('Informe um limite maior que zero.');op={op:'budget',month:limitDraft.month,categoryId:limitDraft.category.id,limit:value};}else if(categoryDraft){if(!categoryDraft.name.trim())throw new Error('Informe o nome da categoria.');op={op:'spendingCategory',...categoryDraft,name:categoryDraft.name.trim()};}else return;setPending(true);if(await save(op)){setLimitDraft(null);setCategoryDraft(null);onDirty(false);}else setError('Não foi possível salvar. Revise a mensagem do aplicativo.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setPending(false);}};
 const remove=async()=>{if(!removing||locked)return;setPending(true);setError('');try{if(await save({op:'deleteBudget',month,categoryId:removing.id}))setRemoving(null);else setError('Não foi possível remover o limite.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível remover.');}finally{setPending(false);}};
 return <div className="budgets-page"><div className="budgets-toolbar"><div><p className="subtle">Planeje seus gastos e acompanhe o mês.</p><label className="budgets-month">Mês do orçamento<input aria-label="Mês do orçamento" type="month" min="1900-01" max="2199-12" value={month} onInput={e=>{const v=e.currentTarget.value;if(v)setMonth(v);}} onChange={e=>{if(e.target.value)setMonth(e.target.value);}} disabled={locked}/></label></div><Button variant="outline" disabled={locked} onClick={()=>setManager(true)}><Tags size={16}/> Categorias de despesas</Button></div>
 <p className="budgets-basis">Despesas realizadas usam a data de pagamento. Despesas planejadas entram como pendentes. Transferências ficam fora do orçamento.</p>
 <div className="budgets-totals">{[{label:'Limites definidos',value:total.limit},{label:'Gasto realizado',value:total.spent},{label:'Pendente',value:total.pending},{label:'Disponível após pendentes',value:total.limit-total.spent-total.pending}].map(x=><section className="panel" key={x.label}><span>{x.label}</span><strong className={x.value<0?'negative':''}>{money(x.value)}</strong></section>)}</div><p className="budgets-scope">Totais acima incluem apenas as {budgeted.length} categorias com limite em {monthLabel(month)}.</p>
 {unbudgeted.some(r=>r.spent+r.pending>0)&&<p className="budgets-unset" role="status"><Wallet size={17}/><span>Despesas sem limite: <strong>{money(unbudgeted.reduce((n,r)=>n+r.spent+r.pending,0))}</strong> em {unbudgetedExpenses.length} despesas de {unbudgeted.filter(r=>r.spent+r.pending>0).length} categorias, incluindo pendentes.</span></p>}
 <div className="budgets-grid">{rows.map(r=>{const over=r.remaining!==null&&r.remaining<0,forecast=r.forecastRemaining!==null&&r.forecastRemaining<0;return <section className={'panel budget-card'+(over?' budget-over':'')} key={r.category.id}><div className="budget-heading"><h2><span style={{background:r.category.color}}/>{r.category.name}</h2><div><Button size="icon" variant="ghost" aria-label={'Editar limite de '+r.category.name} disabled={locked} onClick={()=>openLimit(r.category,r.limit)}><Pencil size={16}/></Button>{r.limit!==null&&<Button size="icon" variant="ghost" aria-label={'Remover limite de '+r.category.name} disabled={locked} onClick={()=>{setRemoving(r.category);setError('');}}><Trash2 size={16}/></Button>}</div></div><div className="budget-amount"><strong>{money(r.spent)}</strong><span>{r.limit!==null?'de '+money(r.limit):'Sem limite definido'}</span></div>{r.limit!==null?<><div className="budget-progress" role="progressbar" aria-label={'Limite utilizado de '+r.category.name} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(100,Math.max(0,r.percent??0))} aria-valuetext={(r.percent??0).toFixed(1)+'% do limite utilizado'}><span style={{width:Math.min(100,Math.max(0,r.percent??0))+'%',background:over?'#da5252':r.category.color}}/></div><p className={over?'negative':'budget-available'}>{over?'Limite ultrapassado em '+money(-(r.remaining??0)):'Disponível: '+money(r.remaining??0)}</p></>:<Button variant="outline" disabled={locked} onClick={()=>openLimit(r.category,null)}><Plus size={15}/> Definir limite</Button>}<div className="budget-pending"><span>Pendente</span><strong>{money(r.pending)}</strong></div>{r.limit!==null&&<p className={forecast?'budget-forecast negative':'budget-forecast'}>{forecast?'Com pendentes, excede em '+money(-(r.forecastRemaining??0)):'Após pendentes: '+money(r.forecastRemaining??0)}</p>}</section>;})}</div>
 <Dialog open={manager} onOpenChange={v=>{if(!locked)setManager(v);}}><DialogContent className="budget-dialog"><DialogHeader><DialogTitle>Categorias de despesas</DialogTitle><DialogDescription>Organize as despesas com nomes e cores que fazem sentido para você.</DialogDescription></DialogHeader><div className="budget-category-list">{categories.map(c=><div key={c.id}><span className="budget-dot" style={{background:c.color}}/><span>{c.name}</span><Button variant="ghost" size="icon" aria-label={'Editar categoria '+c.name} disabled={locked} onClick={()=>openCategory(c)}><Pencil size={16}/></Button></div>)}</div><Button disabled={locked} onClick={()=>openCategory()}><Plus size={16}/> Nova categoria</Button></DialogContent></Dialog>
 <Dialog open={!!limitDraft||!!categoryDraft} onOpenChange={v=>{if(!v)closeEditor();}}><DialogContent className="budget-dialog" showCloseButton={!locked}><DialogHeader><DialogTitle>{limitDraft?'Limite de '+limitDraft.category.name:categoryDraft?.id?'Editar categoria':'Nova categoria'}</DialogTitle><DialogDescription>{limitDraft?'Defina o máximo de despesas para '+monthLabel(limitDraft.month)+'.':'Essa categoria estará disponível para suas despesas e orçamentos.'}</DialogDescription></DialogHeader><form className="editor-form" onSubmit={submit}>{limitDraft&&<label>Limite mensal (R$)<input autoFocus required disabled={locked} inputMode="decimal" value={limitDraft.value} placeholder="Ex.: 1.500,00" onChange={e=>{const d={...limitDraft,value:e.target.value};setLimitDraft(d);onDirty(JSON.stringify(d)!==baseline);}}/></label>}{categoryDraft&&<><label>Nome<input autoFocus required maxLength={80} disabled={locked} value={categoryDraft.name} onChange={e=>{const d={...categoryDraft,name:e.target.value};setCategoryDraft(d);onDirty(JSON.stringify(d)!==baseline);}}/></label><label>Cor<input type="color" disabled={locked} value={categoryDraft.color} onChange={e=>{const d={...categoryDraft,color:e.target.value};setCategoryDraft(d);onDirty(JSON.stringify(d)!==baseline);}}/></label></>}{error&&<p className="negative" role="alert">{error}</p>}<div className="budget-actions"><Button type="button" variant="outline" disabled={locked} onClick={closeEditor}>Cancelar</Button><Button type="submit" disabled={locked}>{locked?'Salvando…':'Salvar'}</Button></div></form></DialogContent></Dialog>
 <Dialog open={!!removing} onOpenChange={v=>{if(!v&&!locked)setRemoving(null);}}><DialogContent showCloseButton={!locked}><DialogHeader><DialogTitle>Remover limite?</DialogTitle><DialogDescription>O limite de {removing?.name} em {monthLabel(month)} será removido. As despesas continuam registradas.</DialogDescription></DialogHeader>{error&&<p role="alert" className="negative">{error}</p>}<div className="budget-actions"><Button variant="outline" disabled={locked} onClick={()=>setRemoving(null)}>Cancelar</Button><Button variant="destructive" disabled={locked} onClick={()=>void remove()}>{locked?'Removendo…':'Remover limite'}</Button></div></DialogContent></Dialog></div>;
}
