'use client';
import { useState } from 'react';
import { Target, Plus, Pencil, Trash2, Check, CalendarDays } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import { goalProgress, inputMoney, money, monthLabel, parseMoney, type Goal, type PortfolioState } from '@/lib/finance';

type Draft={id?:string;name:string;target:string;accountId:string;deadline:string};
type Props={state:PortfolioState;busy:boolean;save:(op:any)=>Promise<boolean>;onDirty:(dirty:boolean)=>void};
export default function Goals({state,busy,save,onDirty}:Props){
 const [draft,setDraft]=useState<Draft|null>(null),[baseline,setBaseline]=useState(''),[error,setError]=useState(''),[deleting,setDeleting]=useState<Goal|null>(null),[deleteError,setDeleteError]=useState(''),[pending,setPending]=useState(false);
 const locked=busy||pending;
 const goals=state.goals??[];
 const open=(goal?:Goal)=>{const next={id:goal?.id,name:goal?.name??'',target:inputMoney(goal?.target),accountId:goal?.accountId??'',deadline:goal?.deadline??''};setDraft(next);setBaseline(JSON.stringify(next));setError('');onDirty(false);};
 const change=(next:Draft)=>{setDraft(next);onDirty(JSON.stringify(next)!==baseline);};
 const close=()=>{if(locked)return;if(draft&&JSON.stringify(draft)!==baseline&&!window.confirm('Descartar as alterações desta meta?'))return;setDraft(null);setError('');onDirty(false);};
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!draft||locked)return;setError('');try{const target=parseMoney(draft.target);if(target===null||target<=0)throw new Error('Informe um valor maior que zero.');if(!draft.name.trim())throw new Error('Informe o nome da meta.');if(draft.deadline&&(!/^\d{4}-(0[1-9]|1[0-2])$/.test(draft.deadline)||draft.deadline<'1900-01'||draft.deadline>'2199-12'))throw new Error('Informe um mês entre 1900 e 2199.');setPending(true);if(await save({op:'goal',id:draft.id,name:draft.name.trim(),target,accountId:draft.accountId||null,deadline:draft.deadline||null})){setDraft(null);onDirty(false);}else setError('Não foi possível salvar. Revise a mensagem do aplicativo e tente novamente.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar a meta.');}finally{setPending(false);}};
 const remove=async()=>{if(!deleting||locked)return;setDeleteError('');setPending(true);try{if(await save({op:'deleteGoal',id:deleting.id}))setDeleting(null);else setDeleteError('Não foi possível excluir a meta. Tente novamente.');}catch(e){setDeleteError(e instanceof Error?e.message:'Não foi possível excluir a meta.');}finally{setPending(false);}};
 const reached=goals.filter(g=>{const p=goalProgress(state,g);return p.remaining===0;}).length;
 return <div className="goals-page"><div className="goals-intro"><div><p className="subtle">Dê um destino ao seu patrimônio.</p><p className="goals-basis">O progresso usa o último fechamento concluído, sem projeções de rendimento.</p></div><Button disabled={locked} onClick={()=>open()}><Plus size={17}/> Nova meta</Button></div>
 {goals.length>0&&<div className="goals-summary"><span><Target size={17}/> {goals.length} {goals.length===1?'meta cadastrada':'metas cadastradas'}</span><span><Check size={17}/> {reached} {reached===1?'alcançada':'alcançadas'}</span></div>}
 {!goals.length?<section className="panel goals-empty"><span className="goals-empty-icon"><Target size={34}/></span><h2>Qual é seu próximo objetivo?</h2><p>Uma reserva de emergência, uma viagem ou um novo começo. Defina um valor e acompanhe seu progresso a cada fechamento.</p><Button disabled={locked} onClick={()=>open()}><Plus size={17}/> Criar minha primeira meta</Button></section>:<div className="goals-grid">{goals.map(goal=>{const p=goalProgress(state,goal),account=state.accounts.find(a=>a.id===goal.accountId),achieved=p.remaining===0,percent=p.percent===null?null:Math.max(0,Math.min(100,p.percent));return <section key={goal.id} className={'panel goal-card'+(achieved?' goal-achieved':'')}><div className="goal-card-heading"><span className="goal-icon">{achieved?<Check size={21}/>:<Target size={21}/>}</span><div className="goal-tools"><Button size="icon" variant="ghost" disabled={locked} aria-label={'Editar meta '+goal.name} onClick={()=>open(goal)}><Pencil size={16}/></Button><Button size="icon" variant="ghost" disabled={locked} aria-label={'Excluir meta '+goal.name} onClick={()=>{setDeleting(goal);setDeleteError('');}}><Trash2 size={16}/></Button></div></div><h2>{goal.name}</h2><p className="goal-scope">{goal.accountId?(account?account.name+(account.archived?' · arquivada':''):'Conta indisponível'):'Patrimônio total'}</p><div className="goal-amount"><strong>{p.value===null?'—':money(p.value)}</strong><span>de {money(goal.target)}</span></div><div className="goal-progress-label"><span>{achieved?<span className="goal-achieved-badge"><Check size={13}/> Meta alcançada</span>:p.percent===null?'Aguardando saldo':p.percent.toFixed(1).replace('.',',')+'% alcançado'}</span><span>{p.remaining===null?'Sem base atual':p.remaining>0?'Faltam '+money(p.remaining):'Objetivo atingido'}</span></div><div className="goal-progress" role="progressbar" aria-label={'Progresso de '+goal.name} aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent??undefined} aria-valuetext={percent===null?'Sem saldo disponível':percent.toFixed(1)+'%'}><span style={{width:(percent??0)+'%'}}/></div><p className="goal-source">{p.value!==null&&p.month?'Base: '+monthLabel(p.month):'Conclua um fechamento com saldo para acompanhar esta meta.'}</p><div className="goal-deadline"><CalendarDays size={16}/><span>{goal.deadline?'Prazo: '+monthLabel(goal.deadline):'Sem prazo definido'}</span></div>{goal.deadline&&!achieved&&<p className="goal-rhythm">{p.monthlyNeeded!==null?<><strong>{money(p.monthlyNeeded)}/mês</strong><span>Ritmo necessário, sem considerar rendimentos.</span></>:p.monthsLeft!==null&&p.monthsLeft<=0?'O prazo chegou. Atualize a meta ou continue acompanhando seu progresso.':'O ritmo necessário aparece quando houver saldo disponível.'}</p>}</section>;})}</div>}
 <Dialog open={!!draft} onOpenChange={isOpen=>{if(!isOpen)close();}}><DialogContent className="goal-dialog" showCloseButton={!locked}><DialogHeader><DialogTitle>{draft?.id?'Editar meta':'Nova meta'}</DialogTitle><DialogDescription>Escolha seu objetivo e o saldo que acompanhará sua evolução.</DialogDescription></DialogHeader>{draft&&<form className="editor-form goal-form" onSubmit={submit}><label>Nome da meta<input autoFocus maxLength={80} required disabled={locked} value={draft.name} onChange={e=>change({...draft,name:e.target.value})} placeholder="Ex.: Reserva de emergência"/></label><label>Valor desejado (R$)<input inputMode="decimal" required disabled={locked} value={draft.target} onChange={e=>change({...draft,target:e.target.value})} placeholder="Ex.: 30.000,00"/></label><label>Acompanhar o saldo de<select disabled={locked} value={draft.accountId} onChange={e=>change({...draft,accountId:e.target.value})}><option value="">Patrimônio total</option>{state.accounts.map(a=><option key={a.id} value={a.id}>{a.name}{a.archived?' · arquivada':''}</option>)}</select></label><label>Prazo (opcional)<input type="month" min="1900-01" max="2199-12" disabled={locked} value={draft.deadline} onInput={e=>change({...draft,deadline:e.currentTarget.value})} onChange={e=>change({...draft,deadline:e.target.value})}/></label><p className="subtle">O prazo serve para calcular o valor que falta por mês, sem considerar rendimentos.</p>{error&&<p className="negative" role="alert">{error}</p>}<div className="goal-form-actions"><Button type="button" variant="outline" disabled={locked} onClick={close}>Cancelar</Button><Button type="submit" disabled={locked}>{locked?'Salvando…':'Salvar meta'}</Button></div></form>}</DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={isOpen=>{if(!isOpen&&!locked)setDeleting(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir meta?</AlertDialogTitle><AlertDialogDescription>A meta “{deleting?.name}” será removida. Seus saldos e fechamentos serão preservados.</AlertDialogDescription></AlertDialogHeader>{deleteError&&<p className="negative" role="alert">{deleteError}</p>}<AlertDialogFooter><AlertDialogCancel disabled={locked}>Cancelar</AlertDialogCancel><AlertDialogAction disabled={locked} onClick={e=>{e.preventDefault();void remove();}}>{locked?'Excluindo…':'Excluir meta'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
