'use client';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { parseMoney,money,investmentResult,type InvestmentMode } from '@/lib/finance';
export type InvestmentDraft={value:string;base:string;investmentMode:InvestmentMode;reportedGain:string;resultSign:'gain'|'loss'};
export function parseInvestment(d:InvestmentDraft){const value=parseMoney(d.value);const base=d.investmentMode==='capital'?parseMoney(d.base):null;const amount=d.investmentMode==='result'?parseMoney(d.reportedGain):null;if(amount!==null&&amount<0)throw new Error('Informe o resultado sem sinal e selecione Ganho ou Perda.');return {value,base,investmentMode:d.investmentMode,reportedGain:amount===null?null:amount*(d.resultSign==='loss'?-1:1)};}
export default function InvestmentFields({draft:d,name,disabled,onChange}:{draft:InvestmentDraft;name:string;disabled:boolean;onChange:(patch:Partial<InvestmentDraft>)=>void}){
 let result:number|null=null;try{result=investmentResult(parseInvestment(d));}catch{}
 return <div className="investment-fields"><label className="investment-mode-label">Como você acompanha este investimento?<Select value={d.investmentMode} disabled={disabled} onValueChange={v=>onChange({investmentMode:v as InvestmentMode})}><SelectTrigger className="w-full" aria-label={'Forma de registro de '+name}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="capital">Sei o capital aplicado</SelectItem><SelectItem value="result">Tenho o ganho ou a perda do app</SelectItem></SelectContent></Select></label><div className="field-grid"><label>Valor atual (R$)<input aria-label={'Valor atual de '+name} inputMode="decimal" disabled={disabled} value={d.value} onChange={e=>onChange({value:e.target.value})} placeholder="0,00"/></label>{d.investmentMode==='capital'?<label>Capital aplicado (R$)<input aria-label={'Capital aplicado de '+name} inputMode="decimal" disabled={disabled} value={d.base} onChange={e=>onChange({base:e.target.value})} placeholder="0,00"/></label>:<label>Resultado informado pelo app (R$)<div className="result-input"><Select value={d.resultSign} disabled={disabled} onValueChange={v=>onChange({resultSign:v as 'gain'|'loss'})}><SelectTrigger aria-label={'Ganho ou perda de '+name}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="gain">Ganho</SelectItem><SelectItem value="loss">Perda</SelectItem></SelectContent></Select><input aria-label={'Resultado informado de '+name} inputMode="decimal" disabled={disabled} value={d.reportedGain} onChange={e=>onChange({reportedGain:e.target.value})} placeholder="0,00"/></div></label>}</div><div className={'investment-result '+(result!==null&&result<0?'loss':'')}><div><small>{d.investmentMode==='capital'?'Resultado calculado':'Resultado informado'}</small><strong className={result!==null&&result<0?'negative':'positive'}>{result===null?'Ainda não informado':money(result)}</strong></div><p>{d.investmentMode==='capital'?'Valor atual menos o capital aplicado.':'Copie o ganho ou a perda exibido pelo app. O capital aplicado permanece desconhecido.'}</p></div>{d.investmentMode==='result'&&<p className="investment-help">Use o mesmo período de referência mostrado pelo aplicativo. Esse resultado não é a variação do saldo entre meses.</p>}</div>;
}
