'use client';
import {useState,type FormEvent} from 'react';
import {ArrowRight,ChartNoAxesCombined,Eye,EyeOff,LockKeyhole,ShieldCheck,LoaderCircle} from 'lucide-react';
import './login.css';
export default function LoginForm(){
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[caps,setCaps]=useState(false);
 async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Não foi possível entrar.');setPassword('');window.location.replace('/');}catch(e){setError(e instanceof Error?e.message:'Não foi possível conectar. Tente novamente.');setBusy(false);}}
 return <main className="login-page"><section className="login-story"><a href="/login" className="login-brand"><span><ChartNoAxesCombined size={27}/></span>saldo<span className="login-dot">.</span></a><div className="login-story-content"><span className="login-eyebrow">SEU PATRIMÔNIO, MÊS A MÊS</span><h1>Clareza hoje. <br/>Perspectiva <br/>para o amanhã.</h1><p>Um espaço só seu para fechar o mês, acompanhar seus investimentos e ver sua evolução.</p><div className="login-illustration" aria-hidden="true"><div><span>Um mês de cada vez</span><ChartNoAxesCombined size={24}/></div><div className="login-bars">{[28,39,36,54,65,77,93].map((height,i)=><i key={i} style={{height:height+'%'}}/>)}</div><footer>REGISTRAR <span>→</span> CONFERIR <span>→</span> EVOLUIR</footer></div></div><small>Organização para suas decisões financeiras.</small></section><section className="login-access"><div className="login-card"><div className="login-lock"><LockKeyhole size={25}/></div><span className="login-eyebrow">ESPAÇO PRIVADO</span><h2>Bom ter você aqui.</h2><p>Entre para acompanhar o seu patrimônio mensal.</p><form onSubmit={submit}><label htmlFor="username">Usuário</label><input id="username" name="username" autoComplete="username" autoCapitalize="none" spellCheck={false} maxLength={100} required value={username} onChange={e=>setUsername(e.target.value)} disabled={busy} placeholder="Seu usuário"/><label htmlFor="password">Senha</label><div className="login-password"><input id="password" name="password" type={show?'text':'password'} autoComplete="current-password" maxLength={1024} required value={password} onChange={e=>setPassword(e.target.value)} onKeyUp={e=>setCaps(e.getModifierState('CapsLock'))} disabled={busy} placeholder="Sua senha"/><button type="button" onClick={()=>setShow(!show)} aria-label={show?'Ocultar senha':'Mostrar senha'} aria-pressed={show}>{show?<EyeOff size={19}/>:<Eye size={19}/>}</button></div>{caps&&<small className="login-caps">Caps Lock está ativado.</small>}{error&&<div role="alert" className="login-error">{error}</div>}<button className="login-submit" disabled={busy} type="submit">{busy?<><LoaderCircle className="animate-spin" size={20}/> Entrando…</>:<>Entrar no meu espaço <ArrowRight size={19}/></>}</button></form><div className="login-security"><ShieldCheck size={18}/><span>Acesso privado. Sua sessão expira após 30 minutos sem atividade.</span></div><p className="login-help">Esqueceu a senha? O responsável pelo servidor pode redefini-la no EasyPanel.</p></div><small className="login-footer">Saldo · Seu fechamento mensal, com clareza.</small></section></main>;
}
