'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {LockKeyhole,ShieldCheck} from 'lucide-react';
import './login.css';
export default function RecoveryForm(){
 const [token,setToken]=useState(''),[username,setUsername]=useState('allexbonilha'),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 const captured=useRef(false);
 useEffect(()=>{if(captured.current)return;captured.current=true;const value=new URLSearchParams(window.location.hash.slice(1)).get('token')||'';setToken(value);window.history.replaceState(null,'','/recover');},[]);
 async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/auth/recover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,username,password,confirmation})});const data=await r.json();if(!r.ok)throw new Error(data.error);setPassword('');setConfirmation('');setToken('');setDone(true);}catch(e){setError(e instanceof Error?e.message:'Não foi possível conectar.');}finally{setBusy(false);}}
 return <main className="login-page"><section className="login-story"><a href="/login" className="login-brand">saldo.</a><div className="login-story-content"><span className="login-eyebrow">SEU ACESSO, PROTEGIDO</span><h1>Um novo acesso.<br/>Seu patrimônio<br/>preservado.</h1><p>Defina sua nova senha diretamente aqui. Seus registros e fechamentos continuam na mesma conta.</p></div></section><section className="login-access"><div className="login-card"><div className="login-lock"><LockKeyhole/></div><h2>{done?'Acesso atualizado.':'Recuperar meu acesso'}</h2>{done?<><p>Sua senha foi redefinida e os acessos anteriores foram encerrados. Entre usando o usuário <strong>{username}</strong> e sua nova senha.</p><a className="login-submit" href="/login">Ir para o login</a></>:<><p>Este link é temporário e funciona uma única vez. Escolha uma senha com pelo menos 16 caracteres.</p>{token?<form onSubmit={submit}><label htmlFor="username">Usuário</label><input id="username" autoComplete="username" autoCapitalize="none" spellCheck={false} minLength={3} maxLength={32} required disabled={busy} value={username} onChange={e=>setUsername(e.target.value)}/><label htmlFor="password">Nova senha</label><input id="password" type="password" autoComplete="new-password" minLength={16} maxLength={128} required disabled={busy} value={password} onChange={e=>setPassword(e.target.value)}/><label htmlFor="confirmation">Confirmar nova senha</label><input id="confirmation" type="password" autoComplete="new-password" minLength={16} maxLength={128} required disabled={busy} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/>{error&&<div role="alert" className="login-error">{error}</div>}<button className="login-submit" disabled={busy}>{busy?'Salvando…':'Salvar meu novo acesso'}</button></form>:<div role="alert" className="login-error">Abra o link de recuperação recebido. Se ele expirou, solicite outro ao responsável pelo aplicativo.</div>}<div className="login-security"><ShieldCheck size={18}/><span>Sua senha fica protegida no banco. A redefinição encerra as sessões antigas.</span></div></>}</div></section></main>;
}
