'use client';
import {CalendarCheck,ClipboardCheck,Download,CheckCircle2,Info,ArrowRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {recordHealth,previousMonth,monthLabel,type PortfolioState} from '@/lib/finance';
export default function RecordHealth({state,onOpen,onExport}:{state:PortfolioState;onOpen:(m:string)=>void;onExport:(kind:'csv'|'json')=>void}){
 const h=recordHealth(state),months:string[]=[];let m=previousMonth();for(let i=0;i<12;i++){months.unshift(m);m=previousMonth(m);}
 const last=state.closings.find(c=>c.month===h.lastClosed),pendingCount=h.drafts.length+h.missingMonths.length;
 return <><div className="tracking-metrics"><div className="metric"><span>Fechamentos concluídos</span><h2>{h.closedCount}</h2><small>{h.lastClosed?'Último: '+monthLabel(h.lastClosed):'Comece pelo mês anterior'}</small></div><div className="metric"><span>Meses a conferir</span><h2>{pendingCount}</h2><small>Rascunhos e lacunas desde o primeiro registro</small></div><div className="metric"><span>Registros incompletos</span><h2>{h.incompleteEntries.length}</h2><small>Campos em branco não são tratados como zero</small></div></div>
 <section className="panel"><div className="section-heading"><div><h2>Seu calendário de fechamentos</h2><p>Últimos 12 meses · clique para conferir ou preencher.</p></div><CalendarCheck size={22}/></div><div className="closing-calendar">{months.map(month=>{const c=state.closings.find(c=>c.month===month);return <button key={month} className={'calendar-month '+(c?.status??'missing')} onClick={()=>onOpen(month)}><strong>{monthLabel(month)}</strong><span>{c?.status==='closed'?'✓ Concluído':c?'Rascunho':'Sem registro'}</span></button>;})}</div></section>
 <div className="tracking-two-cols mt-6"><section className="panel"><div className="section-heading"><div><h2>O que merece atenção</h2><p>Conferências práticas para manter seu histórico confiável.</p></div><ClipboardCheck size={21}/></div>{!pendingCount&&!h.incompleteEntries.length?<div className="health-success"><CheckCircle2/><strong>{state.closings.length?'Seu histórico está em dia.':'Tudo pronto para começar.'}</strong><p>{state.closings.length?'Nenhuma lacuna ou rascunho encontrado.':'Registre um fechamento para começar a acompanhar a evolução.'}</p></div>:<div className="health-list">{h.drafts.map(c=><div key={c.month}><span><strong>{monthLabel(c.month)}</strong><small>Rascunho · falta concluir</small></span><Button variant="ghost" onClick={()=>onOpen(c.month)}>Conferir <ArrowRight size={14}/></Button></div>)}{h.missingMonths.slice(-12).map(month=><div key={month}><span><strong>{monthLabel(month)}</strong><small>Não há registro entre seus fechamentos</small></span><Button variant="ghost" onClick={()=>onOpen(month)}>Preencher <ArrowRight size={14}/></Button></div>)}{h.missingMonths.length>12&&<p className="subtle">Mais {h.missingMonths.length-12} meses sem registro. Use o seletor de mês no fechamento para acessá-los.</p>}{h.incompleteEntries.slice(0,10).map((e,i)=><div key={i}><span><strong>{e.account}</strong><small>{monthLabel(e.month)} · valor ou resultado não informado</small></span><Button variant="ghost" onClick={()=>onOpen(e.month)}>Abrir</Button></div>)}</div>}{h.unknownCapital>0&&<div className="info-note"><Info size={18}/><span>{h.unknownCapital} investimento(s) com capital desconhecido no último fechamento. O resultado informado pelo aplicativo é válido; esses investimentos ficam fora do percentual sobre o capital conhecido.</span></div>}</section>
 <section className="panel"><div className="section-heading"><div><h2>Seus dados, sempre à mão</h2><p>Baixe uma cópia dos registros salvos.</p></div><Download size={21}/></div><div className="backup-option"><strong>Cópia completa</strong><p>JSON com contas, fechamentos, metas, lançamentos e orçamentos. Guarde uma cópia depois de cada fechamento.</p><Button variant="outline" onClick={()=>onExport('json')}><Download size={16}/> Baixar cópia JSON</Button></div><div className="backup-option"><strong>Levar para a planilha</strong><p>CSV com saldos, capital conhecido, resultado e origem de cada valor. Compatível com Excel.</p><Button variant="outline" onClick={()=>onExport('csv')}><Download size={16}/> Exportar CSV</Button></div><p className="subtle text-xs mt-5">{last?'Último fechamento atualizado em '+new Date(last.updatedAt).toLocaleString('pt-BR'): 'Os dados são salvos no banco quando você confirma uma alteração.'}</p></section></div>
 <section className="panel mt-6"><div className="section-heading"><div><h2>Como ler seus números</h2><p>Cada indicador responde a uma pergunta diferente.</p></div></div><div className="tracking-two-cols"><div className="explanation"><strong>Patrimônio e variação mensal</strong><p>O patrimônio soma os valores atuais das contas registradas. A diferença entre fechamentos inclui entradas, saídas e alterações no conjunto de contas; ela não é uma medida de rentabilidade.</p></div><div className="explanation"><strong>Resultado dos investimentos</strong><p>Você pode informar o capital aplicado ou copiar o ganho/perda do aplicativo. Esse resultado pode ser acumulado e ter outro período de referência. O capital nunca é somado novamente ao patrimônio.</p></div><div className="explanation"><strong>Contas arquivadas e histórico</strong><p>Arquivar tira a conta dos novos fechamentos, mantendo os registros anteriores. Se transferir valores entre contas, confira ambas para evitar deixar dinheiro de fora ou contá-lo duas vezes.</p></div><div className="explanation"><strong>Metas e ritmo necessário</strong><p>O progresso usa o último fechamento concluído. O ritmo necessário divide o que falta pelos meses até o prazo; não pressupõe rendimentos nem garante uma projeção.</p></div></div></section></>;
}
