import {applyLifeOperation,lifeOperations,type Transaction,type SpendingCategory,type Budget} from './life.ts';
export type AccountType='balance'|'investment'|'cash';
export type Category={id:string;name:string;color:string};
export type Account={id:string;name:string;categoryId:string;type:AccountType;archived:boolean};
export type InvestmentMode='capital'|'result';
export type BalanceInput={value:number|null;base:number|null;investmentMode?:InvestmentMode;reportedGain?:number|null;type?:AccountType};
export type Entry=BalanceInput & {accountId:string;name:string;categoryId:string;categoryName:string;categoryColor:string;type:AccountType;counts:Record<string,number>;extra:number;mode:'direct'|'count';deposit:number;withdrawal:number};
export type Closing={month:string;status:'draft'|'closed';entries:Entry[];note:string;updatedAt:string;flow?:{income:number|null;expense:number|null}};
export type Goal={id:string;name:string;target:number;accountId:string|null;deadline:string|null};
export type PortfolioState={categories:Category[];accounts:Account[];closings:Closing[];goals?:Goal[];transactions?:Transaction[];spendingCategories?:SpendingCategory[];budgets?:Budget[]};
export type Totals={total:number;invested:number;gain:number};
export type Comparison={difference:number|null;percent:number|null};
export const denominations=[20000,10000,5000,2000,1000,500,200,100,50,25,10,5];
export const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n/100);
export const monthLabel=(m:string)=>new Date(m+'-15T12:00:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'});
export function currentMonth(){const p=new Intl.DateTimeFormat('en',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit'}).formatToParts(new Date());return p.find(p=>p.type==='year')!.value+'-'+p.find(p=>p.type==='month')!.value;}
export function previousMonth(month=currentMonth()){const [y,m]=month.split('-').map(Number);return `${m===1?y-1:y}-${String(m===1?12:m-1).padStart(2,'0')}`;}
function cents(n:unknown){if(!Number.isSafeInteger(n)||Math.abs(n as number)>1e13)throw new Error('Valor fora do limite permitido.');}
export function parseMoney(raw:string):number|null{const s=raw.trim().replace(/^R\$\s*/,'');if(!s)return null;if(!/^-?(?:\d+|\d{1,3}(?:\.\d{3})+)(?:,\d{1,2})?$/.test(s))throw new Error('Informe um valor como 1.234,56.');const n=Math.round(Number(s.replaceAll('.','').replace(',','.'))*100);cents(n);return n;}
export const inputMoney=(n:number|null|undefined)=>n==null?'':(n/100).toFixed(2).replace('.',',');
export function cashTotal(counts:Record<string,number>,extra:number){cents(extra);if(extra<0)throw new Error('Valor adicional não pode ser negativo.');let total=extra;for(const [d,q]of Object.entries(counts)){if(!denominations.includes(Number(d))||!Number.isSafeInteger(q)||q<0||q>100000000)throw new Error('Informe quantidades inteiras e não negativas.');total+=Number(d)*q;}cents(total);return total;}
export function investmentResult(e:BalanceInput):number|null{if(e.value==null)return null;if(e.investmentMode==='result')return e.reportedGain??null;return e.base==null?null:e.value-e.base;}
export function investmentSummary(es:BalanceInput[]){const investments=es.filter(e=>e.type==='investment'||e.base!=null||e.investmentMode!=null);const capitalEntries=investments.filter(e=>e.investmentMode!=='result');const knownCapital=capitalEntries.reduce((n,e)=>n+(e.base??0),0);const capitalGain=capitalEntries.reduce((n,e)=>n+(investmentResult(e)??0),0);return {knownCapital,capitalGain,capitalPercent:knownCapital>0&&capitalEntries.every(e=>investmentResult(e)!==null)?capitalGain/knownCapital*100:null,unknownCapitalCount:investments.filter(e=>e.investmentMode==='result'||e.base==null).length,complete:investments.every(e=>investmentResult(e)!==null)};}
export function calculateTotals(es:BalanceInput[]):Totals{let total=0,invested=0,gain=0;for(const e of es){total+=e.value??0;if(e.investmentMode!=='result')invested+=e.base??0;gain+=investmentResult(e)??0;}cents(total);cents(invested);cents(gain);return {total,invested,gain};}
export function compareTotals(n:number,prev:number|null):Comparison{return {difference:prev===null?null:n-prev,percent:prev==null||prev===0?null:(n-prev)/Math.abs(prev)*100};}
export function initialState():PortfolioState{return {categories:[{id:'cash',name:'Dinheiro físico',color:'#e4a33c'},{id:'bank',name:'Contas',color:'#2184d8'},{id:'invest',name:'Investimentos',color:'#00a57b'}],accounts:[{id:'wallet',name:'Carteira',categoryId:'cash',type:'cash',archived:false},{id:'nubank',name:'Nubank',categoryId:'bank',type:'balance',archived:false},{id:'mp',name:'Mercado Pago',categoryId:'bank',type:'balance',archived:false},{id:'nu-fixed',name:'Nubank · Renda fixa',categoryId:'invest',type:'investment',archived:false},{id:'nu-btc',name:'Nubank · Bitcoin',categoryId:'invest',type:'investment',archived:false},{id:'mp-btc',name:'Mercado Pago · Bitcoin',categoryId:'invest',type:'investment',archived:false}],closings:[]};}
const name=(x:unknown)=>{if(typeof x!=='string'||!x.trim()||x.trim().length>80)throw new Error('Informe um nome de até 80 caracteres.');return x.trim();};
export function applyOperation(source:PortfolioState,op:any):PortfolioState{const s=structuredClone(source);if(!op||typeof op.op!=='string')throw new Error('Operação inválida.');
if(lifeOperations.has(op.op))return applyLifeOperation(s,op);
if(op.op==='category'){const n=name(op.name),color=/^#[a-f0-9]{6}$/i.test(op.color)?op.color:'#2184d8';if(op.id){const c=s.categories.find(c=>c.id===op.id);if(!c)throw new Error('Categoria não encontrada.');Object.assign(c,{name:n,color});}else{if(s.categories.length>=100)throw new Error('Limite de categorias atingido.');s.categories.push({id:crypto.randomUUID(),name:n,color});}}
else if(op.op==='account'){const n=name(op.name);if(!s.categories.some(c=>c.id===op.categoryId))throw new Error('Selecione uma categoria.');if(!['balance','cash','investment'].includes(op.type))throw new Error('Tipo inválido.');if(op.id){const a=s.accounts.find(a=>a.id===op.id);if(!a)throw new Error('Conta não encontrada.');if(a.type!==op.type&&s.closings.some(c=>c.entries.some(e=>e.accountId===a.id)))throw new Error('Contas com histórico conservam seu tipo. Crie outra conta.');Object.assign(a,{name:n,categoryId:op.categoryId,type:op.type});}else{if(s.accounts.length>=300)throw new Error('Limite de contas atingido.');s.accounts.push({id:crypto.randomUUID(),name:n,categoryId:op.categoryId,type:op.type,archived:false});}}
else if(op.op==='archive'){const a=s.accounts.find(a=>a.id===op.id);if(!a||typeof op.archived!=='boolean')throw new Error('Conta inválida.');a.archived=op.archived;}
else if(op.op==='deleteAccount'){if(s.closings.some(c=>c.entries.some(e=>e.accountId===op.id)))throw new Error('Esta conta tem histórico. Arquive-a.');if(s.transactions?.some(t=>t.accountId===op.id||t.toAccountId===op.id))throw new Error('Esta conta tem lançamentos. Arquive-a para preservar seu histórico.');if(s.goals?.some(g=>g.accountId===op.id))throw new Error('Esta conta está vinculada a uma meta. Edite a meta antes de excluir.');s.accounts=s.accounts.filter(a=>a.id!==op.id);}
else if(op.op==='deleteCategory'){if(s.accounts.some(a=>a.categoryId===op.id))throw new Error('Transfira as contas antes de excluir a categoria.');s.categories=s.categories.filter(c=>c.id!==op.id);}
else if(op.op==='goal'){
 const n=name(op.name);cents(op.target);if(op.target<=0)throw new Error('O alvo da meta deve ser maior que zero.');
 const accountId=op.accountId??null,deadline=op.deadline??null;
 if(accountId!==null&&!s.accounts.some(a=>a.id===accountId))throw new Error('Conta da meta não encontrada.');
 if(deadline!==null&&(typeof deadline!=='string'||!/^\d{4}-(0[1-9]|1[0-2])$/.test(deadline)||deadline<'1900-01'||deadline>'2199-12'))throw new Error('Prazo inválido.');
 s.goals??=[];if(op.id){const g=s.goals.find(g=>g.id===op.id);if(!g)throw new Error('Meta não encontrada.');Object.assign(g,{name:n,target:op.target,accountId,deadline});}else{if(s.goals.length>=100)throw new Error('Limite de metas atingido.');s.goals.push({id:crypto.randomUUID(),name:n,target:op.target,accountId,deadline});}
}
else if(op.op==='deleteGoal'){if(!s.goals?.some(g=>g.id===op.id))throw new Error('Meta não encontrada.');s.goals=s.goals.filter(g=>g.id!==op.id);}
else if(op.op==='reopen'){const c=s.closings.find(c=>c.month===op.month);if(!c)throw new Error('Fechamento não encontrado.');c.status='draft';c.updatedAt=new Date().toISOString();}
else if(op.op==='saveMonth'){
if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(op.month)||op.month<'1900-01'||op.month>'2199-12')throw new Error('Mês inválido.');if(!['draft','closed'].includes(op.status))throw new Error('Situação inválida.');if(op.status==='closed'&&op.month>currentMonth())throw new Error('Não é possível concluir meses futuros.');
const existing=s.closings.find(c=>c.month===op.month);if(existing?.status==='closed')throw new Error('Reabra o fechamento antes de editar.');if(!Array.isArray(op.entries)||op.entries.length>300)throw new Error('Saldos inválidos.');const seen=new Set();
const entries:Entry[]=op.entries.map((e:any)=>{const a=s.accounts.find(a=>a.id===e.accountId);if(!a||seen.has(a.id))throw new Error('Conta ausente ou duplicada.');seen.add(a.id);const c=s.categories.find(c=>c.id===a.categoryId)!;const old=existing?.entries.find(x=>x.accountId===a.id);const investmentMode=a.type==='investment'?(e.investmentMode??'capital'):undefined;if(investmentMode!==undefined&&!['capital','result'].includes(investmentMode))throw new Error('Escolha capital aplicado ou resultado informado.');const reportedGain=investmentMode==='result'?(e.reportedGain??null):null;if(reportedGain!==null)cents(reportedGain);const base=a.type==='investment'&&investmentMode==='capital'?(e.base??null):null,counts=e.counts??{},extra=e.extra??0,mode=a.type==='cash'&&e.mode==='count'?'count':'direct';const value=mode==='count'?cashTotal(counts,extra):(e.value??null);if(value!==null){cents(value);if(a.type!=='balance'&&value<0)throw new Error('Dinheiro e investimentos não podem ser negativos.');}if(base!==null){cents(base);if(base<0)throw new Error('Capital aplicado não pode ser negativo.');}const deposit=e.deposit??0,withdrawal=e.withdrawal??0;cents(deposit);cents(withdrawal);if(deposit<0||withdrawal<0)throw new Error('Aportes e retiradas não podem ser negativos.');return {accountId:a.id,name:old?.name??a.name,categoryId:old?.categoryId??c.id,categoryName:old?.categoryName??c.name,categoryColor:old?.categoryColor??c.color,type:a.type,value,base,investmentMode,reportedGain,counts,extra,mode,deposit,withdrawal};});
if(op.status==='closed'){const active=s.accounts.filter(a=>!a.archived);if(!active.length)throw new Error('Adicione pelo menos uma conta.');if(active.some(a=>{const e=entries.find(e=>e.accountId===a.id);return !e||e.value===null||(a.type==='investment'&&investmentResult(e)===null);}))throw new Error('Preencha todas as contas ativas antes de concluir.');}calculateTotals(entries);const note=typeof op.note==='string'?op.note:'';if(note.length>3000)throw new Error('Observação muito longa.');s.closings=s.closings.filter(c=>c.month!==op.month);let flow=existing?.flow;if(op.flow!==undefined){if(!op.flow||typeof op.flow!=='object'||Array.isArray(op.flow))throw new Error('Fluxo mensal inválido.');const income=op.flow.income??null,expense=op.flow.expense??null;for(const v of [income,expense])if(v!==null){cents(v);if(v<0)throw new Error('Receitas e despesas devem ser não negativas.');}flow={income,expense};}s.closings.push({month:op.month,status:op.status,entries,note,updatedAt:new Date().toISOString(),...(flow?{flow}:{})});s.closings.sort((a,b)=>a.month.localeCompare(b.month));
}else throw new Error('Operação desconhecida.');return s;}
export function demoState():PortfolioState{let s=initialState(),m=previousMonth();const ms:string[]=[];for(let i=0;i<8;i++){ms.unshift(m);m=previousMonth(m);}ms.forEach((m,i)=>{const vals=[155000+18000*i,342900+12000*i,281600+17000*i,503595+1178300*i,13800+340*i,72278+4100*i];s=applyOperation(s,{op:'saveMonth',month:m,status:'closed',flow:{income:650000+10000*i,expense:420000+8000*i},note:'Dados de demonstração — valores fictícios.',entries:s.accounts.map((a,j)=>({accountId:a.id,value:vals[j],base:a.type==='investment'?(j===3?500000+1150000*i:j===4?10000:65000+3500*i):null,mode:'direct',...(a.id==='mp-btc'?{base:null,investmentMode:'result',reportedGain:-(1400+150*i)}:{})}))});});return s;}
export function exportCsv(s:PortfolioState){const esc=(v:unknown)=>{let x=String(v??'');if(/^[\s]*[=+@-]/.test(x)&&!/^\-?\d+(,\d{1,2})?$/.test(x))x="'"+x;return '"'+x.replaceAll('"','""')+'"';};const rows=[['Mês','Situação','Categoria','Conta','Saldo (R$)','Capital aplicado conhecido (R$)','Resultado do investimento (R$)','Forma de registro','Observações']];for(const c of s.closings)for(const e of c.entries)rows.push([c.month,c.status==='closed'?'Concluído':'Rascunho',e.categoryName,e.name,inputMoney(e.value),inputMoney(e.base),inputMoney(investmentResult(e)),e.type==='investment'?(e.investmentMode==='result'?'Resultado informado':'Capital aplicado'):'Saldo',c.note]);return '\uFEFF'+rows.map(r=>r.map(esc).join(';')).join('\r\n');}
export const exportJson=(s:PortfolioState)=>JSON.stringify({product:'Saldo',version:1,exportedAt:new Date().toISOString(),...s},null,2);

export function monthDistance(from:string,to:string){const [y,m]=from.split('-').map(Number),[yy,mm]=to.split('-').map(Number);return (yy-y)*12+mm-m;}
export function goalProgress(s:PortfolioState,g:Goal){
 const closing=s.closings.filter(c=>c.status==='closed').sort((a,b)=>a.month.localeCompare(b.month)).at(-1);
 const value=closing?(g.accountId===null?(closing.entries.every(e=>e.value!==null)?calculateTotals(closing.entries).total:null):closing.entries.find(e=>e.accountId===g.accountId)?.value??null):null;
 const remaining=value===null?null:Math.max(0,g.target-value),monthsLeft=closing&&g.deadline?monthDistance(closing.month,g.deadline):null;
 return {value,month:closing?.month??null,percent:value===null?null:Math.max(0,value/g.target*100),remaining,monthsLeft,monthlyNeeded:remaining!==null&&monthsLeft!==null&&monthsLeft>0?Math.ceil(remaining/monthsLeft):null};
}
export function recordHealth(s:PortfolioState,through=previousMonth()){
 const sorted=[...s.closings].sort((a,b)=>a.month.localeCompare(b.month)),closed=sorted.filter(c=>c.status==='closed'),missingMonths:string[]=[];
 const first=sorted.find(c=>c.month<=through)?.month;
 if(first){let cursor=through;for(let i=0;cursor>=first&&i<3600;i++,cursor=previousMonth(cursor))if(!sorted.some(c=>c.month===cursor))missingMonths.unshift(cursor);}
 const incompleteEntries=sorted.flatMap(c=>c.entries.filter(e=>e.value===null||(e.type==='investment'&&investmentResult(e)===null)).map(e=>({month:c.month,account:e.name,status:c.status})));
 const unknownCapital=closed.at(-1)?.entries.filter(e=>e.type==='investment'&&(e.investmentMode==='result'||e.base==null)).length??0;
 return {closedCount:closed.length,drafts:sorted.filter(c=>c.status==='draft'),missingMonths,incompleteEntries,unknownCapital,lastClosed:closed.at(-1)?.month??null};
}





export function monthlyFlow(c?:Closing){const income=c?.flow?.income??null,expense=c?.flow?.expense??null;return {income,expense,net:income===null||expense===null?null:income-expense};}
export function exportMonthlyCsv(s:PortfolioState){const rows=[['Mês','Situação','Patrimônio (R$)','Receitas do mês (R$)','Despesas do mês (R$)','Resultado de caixa (R$)']];for(const c of s.closings){const f=monthlyFlow(c);rows.push([c.month,c.status==='closed'?'Concluído':'Rascunho',inputMoney(calculateTotals(c.entries).total),inputMoney(f.income),inputMoney(f.expense),inputMoney(f.net)]);}return '\uFEFF'+rows.map(r=>r.map(v=>'"'+v.replaceAll('"','""')+'"').join(';')).join('\r\n');}
