import type {PortfolioState} from './finance.ts';
export type SpendingCategory={id:string;name:string;color:string};
export type Budget={month:string;categoryId:string;limit:number};
export type Transaction={id:string;title:string;amount:number;kind:'income'|'expense'|'transfer';date:string;status:'pending'|'done';settledDate:string|null;categoryId:string|null;accountId:string|null;toAccountId:string|null;note:string;seriesId:string|null;occurrence:number;totalOccurrences:number};
const defaults:SpendingCategory[]=[{id:'housing',name:'Moradia',color:'#2184d8'},{id:'food',name:'Alimentação',color:'#e4a33c'},{id:'transport',name:'Transporte',color:'#8064c7'},{id:'health',name:'Saúde',color:'#df7d94'},{id:'leisure',name:'Lazer',color:'#00a57b'},{id:'education',name:'Educação',color:'#589ba8'},{id:'services',name:'Assinaturas e serviços',color:'#a38159'},{id:'other',name:'Outros',color:'#73858e'}];
export const spendingCategories=(s:PortfolioState)=>s.spendingCategories??structuredClone(defaults);
export function todayDate(){const p=new Intl.DateTimeFormat('en',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());return ['year','month','day'].map(k=>p.find(p=>p.type===k)!.value).join('-');}
function validMonth(x:unknown):x is string{return typeof x==='string'&&/^\d{4}-(0[1-9]|1[0-2])$/.test(x)&&x>='1900-01'&&x<='2199-12';}
export function validDate(x:unknown):x is string {return typeof x==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x)&&validMonth(x.slice(0,7))&&!Number.isNaN(new Date(x+'T12:00:00Z').getTime())&&new Date(x+'T12:00:00Z').toISOString().slice(0,10)===x;}
export function addMonthsDate(date:string,n:number){const [y,m,d]=date.split('-').map(Number),first=new Date(Date.UTC(y,m-1+n,1)),last=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate();return `${first.getUTCFullYear()}-${String(first.getUTCMonth()+1).padStart(2,'0')}-${String(Math.min(d,last)).padStart(2,'0')}`;}
export function addDays(date:string,n:number){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
function value(n:unknown){if(!Number.isSafeInteger(n)||(n as number)<=0||(n as number)>1e11)throw new Error('Informe um valor positivo em centavos, dentro do limite.');}
function title(n:unknown){if(typeof n!=='string'||!n.trim()||n.trim().length>80)throw new Error('Informe um nome de até 80 caracteres.');return n.trim();}
export const lifeOperations=new Set(['transaction','transactionStatus','deleteTransaction','spendingCategory','deleteSpendingCategory','budget','deleteBudget']);
export function applyLifeOperation(s:PortfolioState,op:any){
 if(op.op==='spendingCategory'){
  const name=title(op.name);if(typeof op.color!=='string'||!/^#[a-f0-9]{6}$/i.test(op.color))throw new Error('Cor inválida.');s.spendingCategories??=spendingCategories(s);
  if(op.id){const c=s.spendingCategories.find(c=>c.id===op.id);if(!c)throw new Error('Categoria não encontrada.');Object.assign(c,{name,color:op.color});}else{if(s.spendingCategories.length>=100)throw new Error('Limite de categorias atingido.');s.spendingCategories.push({id:crypto.randomUUID(),name,color:op.color});}
 }else if(op.op==='deleteSpendingCategory'){
  if((s.transactions??[]).some(t=>t.categoryId===op.id)||(s.budgets??[]).some(b=>b.categoryId===op.id))throw new Error('Esta categoria tem lançamentos ou orçamento. Edite esses registros antes de excluir.');s.spendingCategories=spendingCategories(s).filter(c=>c.id!==op.id);
 }else if(op.op==='budget'||op.op==='deleteBudget'){
  if(!validMonth(op.month)||!spendingCategories(s).some(c=>c.id===op.categoryId))throw new Error('Mês ou categoria inválidos.');
  s.budgets??=[];if(op.op==='budget'){value(op.limit);s.budgets=s.budgets.filter(b=>b.month!==op.month||b.categoryId!==op.categoryId);if(s.budgets.length>=3600)throw new Error('Limite de orçamentos atingido.');s.budgets.push({month:op.month,categoryId:op.categoryId,limit:op.limit});}else s.budgets=s.budgets.filter(b=>b.month!==op.month||b.categoryId!==op.categoryId);
 }else if(op.op==='deleteTransaction'){
  if(!s.transactions?.some(t=>t.id===op.id))throw new Error('Lançamento não encontrado.');s.transactions=s.transactions.filter(t=>t.id!==op.id);
 }else if(op.op==='transactionStatus'){
  const t=s.transactions?.find(t=>t.id===op.id);if(!t)throw new Error('Lançamento não encontrado.');if(!['done','pending'].includes(op.status))throw new Error('Situação inválida.');const settled=op.status==='done'?(op.settledDate??todayDate()):null;
  if(settled!==null&&(!validDate(settled)||settled>todayDate()))throw new Error('A data realizada deve ser válida e não pode ser futura.');t.status=op.status;t.settledDate=settled;
 }else if(op.op==='transaction'){
  const name=title(op.title);value(op.amount);if(!['income','expense','transfer'].includes(op.kind)||!['pending','done'].includes(op.status)||!validDate(op.date))throw new Error('Tipo, situação ou data inválidos.');
  const accountId=op.accountId??null,toAccountId=op.kind==='transfer'?(op.toAccountId??null):null,categoryId=op.kind==='transfer'?null:(op.categoryId??null);
  for(const id of [accountId,toAccountId])if(id!==null&&!s.accounts.some(a=>a.id===id))throw new Error('Conta não encontrada.');
  if(op.kind==='transfer'&&(!accountId||!toAccountId||accountId===toAccountId))throw new Error('Transferências precisam de duas contas diferentes.');
  if((op.kind==='expense'&&categoryId===null)||(categoryId!==null&&!spendingCategories(s).some(c=>c.id===categoryId)))throw new Error('Selecione uma categoria de gasto válida.');
  const settledDate=op.status==='done'?(op.settledDate??op.date):null;if(settledDate!==null&&(!validDate(settledDate)||settledDate>todayDate()))throw new Error('A data realizada deve ser válida e não pode ser futura.');
  const note=op.note??'';if(typeof note!=='string'||note.length>1000)throw new Error('Observação deve ter até 1.000 caracteres.');
  const occurrences=op.occurrences??1;if(!Number.isInteger(occurrences)||occurrences<1||occurrences>36)throw new Error('Escolha entre 1 e 36 ocorrências mensais.');
  const fields={title:name,amount:op.amount,kind:op.kind,date:op.date,status:op.status,settledDate,categoryId,accountId,toAccountId,note};s.transactions??=[];
  if(op.id){if(occurrences!==1)throw new Error('Edite uma ocorrência de cada vez.');const t=s.transactions.find(t=>t.id===op.id);if(!t)throw new Error('Lançamento não encontrado.');Object.assign(t,fields);}else{
   if(s.transactions.length+occurrences>5000)throw new Error('Limite de lançamentos atingido.');const seriesId=occurrences>1?crypto.randomUUID():null;
   for(let i=0;i<occurrences;i++){const date=addMonthsDate(op.date,i);if(!validDate(date))throw new Error('As ocorrências ultrapassam o período permitido.');s.transactions.push({...fields,id:crypto.randomUUID(),date,status:i===0?op.status:'pending',settledDate:i===0?settledDate:null,seriesId,occurrence:i+1,totalOccurrences:occurrences});}
  }
 }
 return s;
}
export function cashflow(s:PortfolioState,month:string){let income=0,expense=0,pendingIncome=0,pendingExpense=0;for(const t of s.transactions??[]){if(t.kind==='transfer')continue;if(t.status==='done'&&t.settledDate?.slice(0,7)===month){if(t.kind==='income')income+=t.amount;else expense+=t.amount;}else if(t.status==='pending'&&t.date.slice(0,7)===month){if(t.kind==='income')pendingIncome+=t.amount;else pendingExpense+=t.amount;}}return {income,expense,net:income-expense,pendingIncome,pendingExpense,expectedNet:income-expense+pendingIncome-pendingExpense};}
export function budgetSummary(s:PortfolioState,month:string){return spendingCategories(s).map(category=>{const limit=s.budgets?.find(b=>b.month===month&&b.categoryId===category.id)?.limit??null;const ts=(s.transactions??[]).filter(t=>t.kind==='expense'&&t.categoryId===category.id);const spent=ts.filter(t=>t.status==='done'&&t.settledDate?.slice(0,7)===month).reduce((n,t)=>n+t.amount,0),pending=ts.filter(t=>t.status==='pending'&&t.date.slice(0,7)===month).reduce((n,t)=>n+t.amount,0);return {category,limit,spent,pending,remaining:limit===null?null:limit-spent,forecastRemaining:limit===null?null:limit-spent-pending,percent:limit===null?null:spent/limit*100};});}
export function exportTransactionsCsv(s:PortfolioState){const esc=(v:unknown)=>{let x=String(v??'');if(/^[\s]*[=+@-]/.test(x))x="'"+x;return '"'+x.replaceAll('"','""')+'"';};const rows=[['Descrição','Tipo','Valor (R$)','Data prevista','Situação','Data realizada','Categoria','Conta','Destino','Ocorrência','Observação']];for(const t of s.transactions??[])rows.push([t.title,{income:'Receita',expense:'Despesa',transfer:'Transferência'}[t.kind],(t.amount/100).toFixed(2).replace('.',','),t.date,t.status==='done'?'Realizado':'Pendente',t.settledDate??'',spendingCategories(s).find(c=>c.id===t.categoryId)?.name??'',s.accounts.find(a=>a.id===t.accountId)?.name??'',s.accounts.find(a=>a.id===t.toAccountId)?.name??'',`${t.occurrence}/${t.totalOccurrences}`,t.note]);return '\uFEFF'+rows.map(r=>r.map(esc).join(';')).join('\r\n');}
export function seedLifeDemo(s:PortfolioState){const month=todayDate().slice(0,7),today=todayDate(),future=addDays(today,3);applyLifeOperation(s,{op:'transaction',title:'Salário',amount:650000,kind:'income',date:month+'-01',status:'done',settledDate:month+'-01',categoryId:null,note:'Exemplo fictício'});for(const [title,amount,categoryId]of [['Mercado',48000,'food'],['Internet',9900,'services'],['Combustível',22000,'transport']] as const)applyLifeOperation(s,{op:'transaction',title,amount,categoryId,kind:'expense',date:today,status:'done',settledDate:today,note:''});applyLifeOperation(s,{op:'transaction',title:'Aluguel',amount:180000,kind:'expense',date:future,status:'pending',categoryId:'housing',note:'',occurrences:6});applyLifeOperation(s,{op:'transaction',title:'Assinatura de exemplo',amount:4990,kind:'expense',date:addDays(today,-2),status:'pending',categoryId:'services',note:''});for(const [categoryId,limit]of [['housing',200000],['food',80000],['services',12000],['transport',40000]] as const)applyLifeOperation(s,{op:'budget',month,categoryId,limit});return s;}
